// File: messaging_app/Jenkinsfile

pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/Binyam0911455745/alx-backend-python.git', credentialsId: 'github-credentials'
            }
        }

        stage('Build and Test') {
            steps {
                echo 'Creating Python virtual environment...'
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate'

                echo 'Installing dependencies...'
                sh 'pip3 install -r messaging_app/requirements.txt'
                sh 'pip3 install pytest'

                echo 'Running tests...'
                sh 'pytest --junitxml=test-reports/report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh "docker build -t binyamtilahu/messaging-app:latest ."
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                    sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
                    sh 'docker push binyamtilahu/messaging-app:latest'
                }
            }
        }

        stage('Publish Test Report') {
            steps {
                echo 'Publishing test report...'
                junit 'test-reports/report.xml'
            }
        }
    }
}