# alx-backend-python/messaging_app/messaging_app/urls.py

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter # Import DefaultRouter

# Import JWT views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from chats import views # Import views from your chats app

# Create a router instance
router = DefaultRouter()

# Register your ConversationViewSet with the router
# This will handle /api/conversations/ and /api/conversations/<uuid>/
router.register(r'conversations', views.ConversationViewSet, basename='conversation')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')), # For optional browsable API login/logout

    # Include all URLs generated by the router for conversations
    path('api/', include(router.urls)),

    # Explicitly define paths for MessageList and MessageDetail
    # These are nested under conversations using the conversation_pk
    # Since MessageList and MessageDetail are generics.ListCreateAPIView and
    # generics.RetrieveUpdateDestroyAPIView respectively, they use .as_view()
    path('api/conversations/<uuid:conversation_pk>/messages/',
         views.MessageList.as_view(),
         name='message-list'), # Name for list and create operations

    path('api/conversations/<uuid:conversation_pk>/messages/<uuid:message_id>/',
         views.MessageDetail.as_view(),
         name='message-detail'), # Name for retrieve, update, delete operations

    # JWT Authentication Endpoints
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]