# messaging_app/chats/urls.py

from django.contrib import admin
from django.urls import path, include
from rest_framework_nested import routers # <-- NEW IMPORT: From rest_framework_nested!

from . import views # Import views from the current app

# 1. Create a DefaultRouter for top-level resources (Conversations)
router = routers.DefaultRouter()
router.register(r'conversations', views.ConversationViewSet, basename='conversation')

# 2. Create a NestedDefaultRouter for Messages, nested under Conversations
conversations_router = routers.NestedDefaultRouter(router, r'conversations', lookup='conversation')
conversations_router.register(r'messages', views.MessageViewSet, basename='conversation-message')


# Define the URL patterns for your chats app
urlpatterns = [
    # Include all URLs generated by the top-level router (e.g., /conversations/, /conversations/<uuid>/)
    path('', include(router.urls)),
    # Include all URLs generated by the nested router (e.g., /conversations/<uuid>/messages/, /conversations/<uuid>/messages/<uuid>/)
    path('', include(conversations_router.urls)),
]
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('chats.urls')), # Includes all chat API URLs
    path('api-auth/', include('rest_framework.urls')), # <-- ADD THIS LINE: Adds DRF login/logout URLs
]