# messaging_app/chats/urls.py

from django.urls import path, include # <-- This line contains 'include'
from rest_framework.routers import DefaultRouter # <-- This line contains 'routers.DefaultRouter()'

from . import views # Import views from the current app

# Create a router instance for your API
router = DefaultRouter() # <-- Instance of DefaultRouter()

# Register your ViewSets with the router
# The first argument is the URL prefix, the second is your ViewSet
router.register(r'conversations', views.ConversationViewSet, basename='conversation')

# Define the URL patterns for your chats app
urlpatterns = [
    # Include all URLs generated by the router (e.g., /conversations/, /conversations/<uuid>/)
    path('', include(router.urls)),

    # Manually define the nested messages endpoint.
    # This path links to the MessageViewSet.
    # 'conversation_pk' will be captured from the URL and used by MessageViewSet's get_queryset.
    path('conversations/<uuid:conversation_pk>/messages/',
         views.MessageViewSet.as_view({'get': 'list', 'post': 'create'}),
         name='message-list-create'),
]