#!/usr/bin/env python3
"""
Fixtures for GithubOrgClient integration tests.
"""

# Example payloads - these would typically come from actual API responses
# or be simplified versions for testing purposes.

ORG_PAYLOAD = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "events_url": "https://api.github.com/orgs/google/events",
    "hooks_url": "https://api.github.com/orgs/google/hooks",
    "issues_url": "https://api.github.com/orgs/google/issues",
    "members_url": "https://api.github.com/orgs/google/members{/member}",
    "public_members_url": "https://api.github.com/orgs/google/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
    "description": "Google’s Open Source projects",
    "name": "Google",
    "company": None,
    "blog": "https://opensource.google/",
    "location": "Mountain View, CA",
    "email": None,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 1780,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "html_url": "https://github.com/google",
    "created_at": "2012-01-21T02:26:07Z",
    "updated_at": "2024-07-16T15:28:44Z",
    "type": "Organization",
    "site_admin": False
}

REPOS_PAYLOAD = [
    {
        "id": 12345,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMjM0NQ==",
        "name": "google-test-repo",
        "full_name": "google/google-test-repo",
        "private": False,
        "owner": ORG_PAYLOAD,
        "html_url": "https://github.com/google/google-test-repo",
        "description": "A test repository for Google.",
        "fork": False,
        "url": "https://api.github.com/repos/google/google-test-repo",
        "forks_url": "https://api.github.com/repos/google/google-test-repo/forks",
        "keys_url": "https://api.github.com/repos/google/google-test-repo/keys{/keyId}",
        "collaborators_url": "https://api.github.com/repos/google/google-test-repo/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/google/google-test-repo/teams",
        "hooks_url": "https://api.github.com/repos/google/google-test-repo/hooks",
        "issue_events_url": "https://api.github.com/repos/google/google-test-repo/issues/events{/number}",
        "events_url": "https://api.github.com/repos/google/google-test-repo/events",
        "assignees_url": "https://api.github.com/repos/google/google-test-repo/assignees{/user}",
        "branches_url": "https://api.github.com/repos/google/google-test-repo/branches{/branch}",
        "tags_url": "https://api.github.com/repos/google/google-test-repo/tags",
        "blobs_url": "https://api.github.com/repos/google/google-test-repo/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/google-test-repo/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/google-test-repo/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/google/google-test-repo/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/google/google-test-repo/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/google/google-test-repo/languages",
        "stargazers_url": "https://api.github.com/repos/google/google-test-repo/stargazers",
        "contributors_url": "https://api.github.com/repos/google/google-test-repo/contributors",
        "subscribers_url": "https://api.github.com/repos/google/google-test-repo/subscribers",
        "subscription_url": "https://api.github.com/repos/google/google-test-repo/subscription",
        "commits_url": "https://api.github.com/repos/google/google-test-repo/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/google/google-test-repo/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/google/google-test-repo/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/google/google-test-repo/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/google/google-test-repo/contents/{+path}",
        "compare_url": "https://api.github.com/repos/google/google-test-repo/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/google/google-test-repo/merges",
        "archive_url": "https://api.github.com/repos/google/google-test-repo/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/google/google-test-repo/downloads",
        "issues_url": "https://api.github.com/repos/google/google-test-repo/issues{/number}",
        "pulls_url": "https://api.github.com/repos/google/google-test-repo/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/google/google-test-repo/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/google-test-repo/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/google/google-test-repo/labels{/name}",
        "releases_url": "https://api.github.com/repos/google/google-test-repo/releases{/id}",
        "deployments_url": "https://api.github.com/repos/google/google-test-repo/deployments",
        "created_at": "2018-01-01T00:00:00Z",
        "updated_at": "2024-07-16T15:28:44Z",
        "pushed_at": "2024-07-16T15:28:44Z",
        "git_url": "git://github.com/google/google-test-repo.git",
        "ssh_url": "git@github.com:google/google-test-repo.git",
        "clone_url": "https://github.com/google/google-test-repo.git",
        "svn_url": "https://svn.github.com/google/google-test-repo",
        "homepage": None,
        "size": 100,
        "stargazers_count": 50,
        "watchers_count": 50,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "has_discussions": False,
        "forks_count": 10,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 2,
        "license": {"key": "mit", "name": "MIT License", "spdx_id": "MIT", "url": "https://api.github.com/licenses/mit", "node_id": "MDc6TGljZW5zZTEz"},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 10,
        "open_issues": 2,
        "watchers": 50,
        "default_branch": "main"
    },
    {
        "id": 67890,
        "node_id": "MDEwOlJlcG9zaXRvcnk2Nzg5MA==",
        "name": "apache2-repo",
        "full_name": "google/apache2-repo",
        "private": False,
        "owner": ORG_PAYLOAD,
        "html_url": "https://github.com/google/apache2-repo",
        "description": "A repository with Apache-2.0 license.",
        "fork": False,
        "url": "https://api.github.com/repos/google/apache2-repo",
        "forks_url": "https://api.github.com/repos/google/apache2-repo/forks",
        "keys_url": "https://api.github.com/repos/google/apache2-repo/keys{/keyId}",
        "collaborators_url": "https://api.github.com/repos/google/apache2-repo/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/google/apache2-repo/teams",
        "hooks_url": "https://api.github.com/repos/google/apache2-repo/hooks",
        "issue_events_url": "https://api.github.com/repos/google/apache2-repo/issues/events{/number}",
        "events_url": "https://api.github.com/repos/google/apache2-repo/events",
        "assignees_url": "https://api.github.com/repos/google/apache2-repo/assignees{/user}",
        "branches_url": "https://api.github.com/repos/google/apache2-repo/branches{/branch}",
        "tags_url": "https://api.github.com/repos/google/apache2-repo/tags",
        "blobs_url": "https://api.github.com/repos/google/apache2-repo/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/apache2-repo/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/apache2-repo/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/google/apache2-repo/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/google/apache2-repo/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/google/apache2-repo/languages",
        "stargazers_url": "https://api.github.com/repos/google/apache2-repo/stargazers",
        "contributors_url": "https://api.github.com/repos/google/apache2-repo/contributors",
        "subscribers_url": "https://api.github.com/repos/google/apache2-repo/subscribers",
        "subscription_url": "https://api.github.com/repos/google/apache2-repo/subscription",
        "commits_url": "https://api.github.com/repos/google/apache2-repo/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/google/apache2-repo/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/google/apache2-repo/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/google/apache2-repo/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/google/apache2-repo/contents/{+path}",
        "compare_url": "https://api.github.com/repos/google/apache2-repo/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/google/apache2-repo/merges",
        "archive_url": "https://api.github.com/repos/google/apache2-repo/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/google/apache2-repo/downloads",
        "issues_url": "https://api.github.com/repos/google/apache2-repo/issues{/number}",
        "pulls_url": "https://api.github.com/repos/google/apache2-repo/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/google/apache2-repo/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/apache2-repo/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/google/apache2-repo/labels{/name}",
        "releases_url": "https://api.github.com/repos/google/apache2-repo/releases{/id}",
        "deployments_url": "https://api.github.com/repos/google/apache2-repo/deployments",
        "created_at": "2019-01-01T00:00:00Z",
        "updated_at": "2024-07-16T15:28:44Z",
        "pushed_at": "2024-07-16T15:28:44Z",
        "git_url": "git://github.com/google/apache2-repo.git",
        "ssh_url": "git@github.com:google/apache2-repo.git",
        "clone_url": "https://github.com/google/apache2-repo.git",
        "svn_url": "https://svn.github.com/google/apache2-repo",
        "homepage": None,
        "size": 200,
        "stargazers_count": 70,
        "watchers_count": 70,
        "language": "Java",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "has_discussions": False,
        "forks_count": 20,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 5,
        "license": {"key": "apache-2.0", "name": "Apache License 2.0", "spdx_id": "Apache-2.0", "url": "https://api.github.com/licenses/apache-2.0", "node_id": "MDc6TGljZW5zZTM="},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 20,
        "open_issues": 5,
        "watchers": 70,
        "default_branch": "main"
    }
]

EXPECTED_REPOS = [
    "google-test-repo",
    "apache2-repo",
]

APACHE2_REPOS = [
    "apache2-repo",
]