services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'myuser'
      # You can use a more complex password here
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'mypassword'
    ports:
      # <Host port>:<Container port>
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: