services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'mypassword'
    volumes:
      - my-db:/var/lib/mysql # This line links the volume
    ports:
      - '3307:3306'

volumes:
  my-db: