#!/bin/bash

# 1. Scale the number of replicas to 3
echo "Scaling the 'messaging-app-deployment' to 3 replicas..."
kubectl scale deployment messaging-app-deployment --replicas=3

# 2. Verify that 3 pods are running
echo "Verifying the pod count..."
kubectl get pods

# 3. Perform a basic load test using 'wrk'
# First, get the URL of the service
echo "Getting the service URL for load testing..."
SERVICE_URL=$(minikube service messaging-app-service --url)

# Perform a load test on the service for 10 seconds
echo "Running a load test with 'wrk' for 10 seconds..."
wrk -t4 -c100 -d10s "${SERVICE_URL}/api/"

# 4. Monitor resource usage
echo "Monitoring resource usage of the pods..."
kubectl top pods
