#!/bin/bash

# Scale the deployment to 3 replicas
kubectl scale deployment messaging-app-deployment --replicas=3

# Verify the number of running pods
kubectl get pods

# Get the service URL and perform a load test
SERVICE_URL=* service default/messaging-app-service has no node port
http://127.0.0.1:56499
wrk -t4 -c100 -d10s "${SERVICE_URL}/api/"

# Monitor resource usage
kubectl top pods
